spring:
  datasource:
    url: jdbc:mysql://localhost:3306/swisscom
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    consumer:
      auto-offset-reset: earliest
